---
title: "Covid-19 Pandemic Time-Series Analysis"
author: "Nitesh Chavan"
date: "September 29, 2025"
output: html_document
---

```{r}
#install.packages("lubridate")
```

```{r}
library(lubridate)
x <- c(580, 7813, 28266, 59287, 75700,
       87820, 95314, 126214, 218843, 471497,
       936851, 1508725, 2072113)
mts <- ts(x, start = decimal_date(ymd("2020-01-22")), frequency = 365.25 / 7)
plot(mts, xlab = "Weekly Data", ylab = "Total +ve Cases",
     main = "COVID-19 Pandemic", col.main = "darkgreen")
```

```{r}
library(lubridate)
positiveCases <- c(580, 7813, 28266, 59287,
                   75700, 87820, 95314, 126214,
                   218843, 471497, 936851,
                   1508725, 2072113)
deaths <- c(17, 270, 565, 1261, 2126, 2800,
            3285, 4628, 8951, 21283, 47210,
            88480, 138475)

mts <- ts(cbind(positiveCases, deaths),
          start = decimal_date(ymd("2020-01-22")),
          frequency = 365.25 / 7)
plot(mts,xlab="Weekly Data",main="Covid-19 Cases",col.main="darkgreen")

```

```{r}
#install.packages("forecast")
```

```{r}
library(lubridate)
library(forecast)

x <- c(580, 7813, 28266, 59287, 75700,
       87820, 95314, 126214, 218843,
       471497, 936851, 1508725, 2072113)

mts <- ts(x, start = decimal_date(ymd("2020-01-22")), frequency = 365.25 / 7)
fit <- auto.arima(mts)
forecasted_values <- forecast(fit, 5)
print(forecasted_values)
```

```{r}
plot(forecasted_values, xlab = "Weekly Data", ylab = "Total +Ve Cases",
     main = "COVID-19 Pandemic", col.main = "darkgreen")
```

```{r}
library(lubridate)
library(forecast)

deaths  <-c(17, 270, 565, 1261, 2126, 2800,
            3285, 4628, 8951, 21283, 47210,
            88480, 138475)
print(x)
mts <- ts(deaths,start=decimal_date(ymd("2020-01-22")),frequency=365.25/7)
fit <- auto.arima(mts)
forecasted_values <- forecast(fit,5)
print(forecasted_values)
```

```{r}
plot(forecasted_values,xlab = "Weekly Data",ylab="Total Deaths",main="Covid-19 Pandemic",col.main = "darkblue")
```
